name: 'Terraform CI CD'

on: 
  workflow_dispatch:
  push:
    branches:
    - main
 


jobs:
  terraform_plan:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      run: terraform init
      env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}


    - name: Terraform Plan
      run: terraform plan
      env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          
  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform_plan
    
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      run: terraform init
      env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIAL }}
          
    - name: Project Done!!!
      run: echo SUCCESS!!!
      
